/**
 * MessageCronTrigger + MessageCronBadge — AionUi port.
 *
 * Originally from
 *   packages/desktop/src/renderer/pages/conversation/Messages/components/MessageCronTrigger.tsx
 *   packages/desktop/src/renderer/pages/conversation/Messages/components/MessageCronBadge.tsx
 *
 * When a scheduled task fires, the gateway emits a `cron_trigger`
 * artifact into the active conversation so the user can see the
 * context ("this message was generated by the morning digest job").
 * The card is a clickable row that navigates to the scheduled-task
 * detail view (route `/scheduled/<cronJobId>` in AionUi, `/cron/<id>`
 * in IntentLoom — the route is not implemented yet, the click
 * currently does nothing).
 *
 * `MessageCronBadge` is a smaller inline pill used inside assistant
 * text to flag "this message was generated by cron job #X" without
 * taking up the full row.
 */

import { AlarmClock, ChevronRight } from "lucide-react";

export interface MessageCronTriggerProps {
  id: string;
  cronJobId?: string;
  cronJobName?: string;
  triggeredAt?: number;
  agentId?: string;
  onNavigate?: (cronJobId: string) => void;
}

function formatTriggeredAt(ts?: number): string | undefined {
  if (!ts || !Number.isFinite(ts)) return undefined;
  const d = new Date(ts);
  if (Number.isNaN(d.getTime())) return undefined;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function MessageCronTrigger(props: MessageCronTriggerProps) {
  const { id, cronJobId, cronJobName, triggeredAt, agentId, onNavigate } = props;

  const handleClick = () => {
    if (cronJobId) onNavigate?.(cronJobId);
  };

  const time = formatTriggeredAt(triggeredAt);
  const label = cronJobName
    ? `定时任务「${cronJobName}」已触发`
    : "定时任务已触发";

  return (
    <div
      className="message-cron-trigger"
      data-testid="message-cron-trigger"
      data-cron-job-id={cronJobId ?? ""}
      data-cron-triggered-at={triggeredAt ?? ""}
      role="button"
      tabIndex={0}
      onClick={handleClick}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          handleClick();
        }
      }}
    >
      <span className="message-cron-trigger__icon" aria-hidden="true">
        <AlarmClock size={16} />
      </span>
      <span className="message-cron-trigger__label">{label}</span>
      {time && <span className="message-cron-trigger__time">{time}</span>}
      <span className="message-cron-trigger__chevron" aria-hidden="true">
        <ChevronRight size={14} />
      </span>
      {agentId && <span className="message-cron-trigger__agent" data-agent-id={agentId} />}
      <span className="sr-only" data-message-id={id} />
    </div>
  );
}

export interface MessageCronBadgeProps {
  cronJobName?: string;
  cronJobId?: string;
}

export function MessageCronBadge({ cronJobName, cronJobId }: MessageCronBadgeProps) {
  return (
    <span
      className="message-cron-badge"
      data-testid="message-cron-badge"
      data-cron-job-id={cronJobId ?? ""}
    >
      <AlarmClock size={10} />
      <span>{cronJobName ? `定时任务: ${cronJobName}` : "定时任务"}</span>
    </span>
  );
}

export default MessageCronTrigger;
