#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// `Manager` trait 提供 .manage() / .state() 等 runtime 接口, tauri::App <R> 与 tauri::AppHandle 都实现它
use tauri::Manager;

mod commands;
mod db;
mod types;
mod utils;

// Local-CLI adapter registry. Each adapter (claude, gemini, codex,
// opencode, openclaw) lives in `src/agents/` and implements
// `agents::AgentAdapter`. The Tauri commands in `commands::agents` and
// `commands::ai` both consult this registry to look up identity and
// binary resolution.
pub mod agents;
pub mod cc_switch;
// Re-exports so cc_switch's internal callers can use `crate::refresh_tray_menu`,
// `crate::quit_app`, etc. (the original cc-switch top-level entry points).
// IntentLoom doesn't need any of these itself — they're called only by
// the cc_switch code paths — but the names are referenced from inside
// `crate::cc_switch::commands::*` so we re-export them at the crate root.
pub use cc_switch::{
    refresh_tray_menu, quit_app, set_tray_icon_enabled, schedule_tray_refresh,
    restart_process, save_window_state_before_exit,
};

pub mod skills;

use std::panic;

pub fn run() {
    // Set panic hook
    panic::set_hook(Box::new(|panic_info| {
        eprintln!("Application panic: {}", panic_info);
    }));

    // Logging is wired up by tauri-plugin-log below; setting up a
    // tracing subscriber here as well would race with the plugin and
    // panic on second `set_logger` with "attempted to set a logger
    // after the logging system was already initialized". Pre-existing
    // IntentLoom bug, not related to the skills migration.

    println!("IntentLoom starting...");

    // Initialize database
    db::init();

    println!("Building Tauri...");

    tauri::Builder::default()
        .manage(commands::ai::AiProcessRegistry::default())
    .manage(crate::agents::config::AgentConfigStore::load(
        &dirs::data_local_dir().unwrap_or_else(|| std::path::PathBuf::from(".")),
    ))
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_process::init())
        // .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_single_instance::init(|_app, _argv, _cwd| {}))
        // 关键: 在 invoke_handler 之前初始化 cc-switch 的 SQLite + AppState 并 manage()
        .setup(|app| {
            // 关键: 把 cc-switch 的 SQLite + AppState 初始化并 manage() 给 Tauri runtime,
            // 否则 invoke("cc_switch_*") 全部 "state not found"
            // —— 用户说"没有真正融合"的根因。
            let state = match cc_switch::init::setup() {
                Ok(s) => s,
                Err(e) => {
                    return Err(Box::new(std::io::Error::new(
                        std::io::ErrorKind::Other,
                        format!("cc_switch init failed: {e}"),
                    )));
                }
            };
            app.manage(state);
            tracing::info!("cc-switch::init::setup() 完成, AppState 已 manage()");
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            cc_switch::commands::balance::cc_switch_get_balance,
            cc_switch::commands::coding_plan::cc_switch_get_coding_plan_quota,
            cc_switch::commands::config::cc_switch_extract_common_config_snippet,
            cc_switch::commands::config::cc_switch_get_app_config_path,
            cc_switch::commands::config::cc_switch_get_claude_code_config_path,
            cc_switch::commands::config::cc_switch_get_claude_common_config_snippet,
            cc_switch::commands::config::cc_switch_get_claude_config_status,
            cc_switch::commands::config::cc_switch_get_common_config_snippet,
            cc_switch::commands::config::cc_switch_get_config_dir,
            cc_switch::commands::config::cc_switch_get_config_status,
            cc_switch::commands::config::cc_switch_open_app_config_folder,
            cc_switch::commands::config::cc_switch_open_config_folder,
            cc_switch::commands::config::cc_switch_pick_directory,
            cc_switch::commands::config::cc_switch_set_claude_common_config_snippet,
            cc_switch::commands::config::cc_switch_set_common_config_snippet,
            cc_switch::commands::copilot::cc_switch_copilot_get_auth_status,
            cc_switch::commands::copilot::cc_switch_copilot_get_models,
            cc_switch::commands::copilot::cc_switch_copilot_get_models_for_account,
            cc_switch::commands::copilot::cc_switch_copilot_get_token,
            cc_switch::commands::copilot::cc_switch_copilot_get_usage,
            cc_switch::commands::copilot::cc_switch_copilot_get_usage_for_account,
            cc_switch::commands::copilot::cc_switch_copilot_is_authenticated,
            cc_switch::commands::copilot::cc_switch_copilot_list_accounts,
            cc_switch::commands::copilot::cc_switch_copilot_logout,
            cc_switch::commands::copilot::cc_switch_copilot_remove_account,
            cc_switch::commands::copilot::cc_switch_copilot_start_device_flow,
            cc_switch::commands::deeplink::cc_switch_import_from_deeplink,
            cc_switch::commands::deeplink::cc_switch_import_from_deeplink_unified,
            cc_switch::commands::deeplink::cc_switch_merge_deeplink_config,
            cc_switch::commands::deeplink::cc_switch_parse_deeplink,
            cc_switch::commands::env::cc_switch_check_env_conflicts,
            cc_switch::commands::env::cc_switch_delete_env_vars,
            cc_switch::commands::env::cc_switch_restore_env_backup,
            cc_switch::commands::failover::cc_switch_add_to_failover_queue,
            cc_switch::commands::failover::cc_switch_get_auto_failover_enabled,
            cc_switch::commands::failover::cc_switch_get_available_providers_for_failover,
            cc_switch::commands::failover::cc_switch_get_failover_queue,
            cc_switch::commands::failover::cc_switch_remove_from_failover_queue,
            cc_switch::commands::failover::cc_switch_set_auto_failover_enabled,
            cc_switch::commands::global_proxy::cc_switch_get_global_proxy_url,
            cc_switch::commands::global_proxy::cc_switch_get_upstream_proxy_status,
            cc_switch::commands::global_proxy::cc_switch_scan_local_proxies,
            cc_switch::commands::global_proxy::cc_switch_set_global_proxy_url,
            cc_switch::commands::global_proxy::cc_switch_test_proxy_url,
            cc_switch::commands::hermes::cc_switch_get_hermes_live_provider,
            cc_switch::commands::hermes::cc_switch_get_hermes_live_provider_ids,
            cc_switch::commands::hermes::cc_switch_get_hermes_memory,
            cc_switch::commands::hermes::cc_switch_get_hermes_memory_limits,
            cc_switch::commands::hermes::cc_switch_get_hermes_model_config,
            cc_switch::commands::hermes::cc_switch_import_hermes_providers_from_live,
            cc_switch::commands::hermes::cc_switch_launch_hermes_dashboard,
            cc_switch::commands::hermes::cc_switch_open_hermes_web_ui,
            cc_switch::commands::hermes::cc_switch_set_hermes_memory,
            cc_switch::commands::hermes::cc_switch_set_hermes_memory_enabled,
            cc_switch::commands::import_export::cc_switch_create_db_backup,
            cc_switch::commands::import_export::cc_switch_delete_db_backup,
            cc_switch::commands::import_export::cc_switch_export_config_to_file,
            cc_switch::commands::import_export::cc_switch_import_config_from_file,
            cc_switch::commands::import_export::cc_switch_list_db_backups,
            cc_switch::commands::import_export::cc_switch_rename_db_backup,
            cc_switch::commands::import_export::cc_switch_restore_db_backup,
            cc_switch::commands::import_export::cc_switch_sync_current_providers_live,
            cc_switch::commands::lightweight::cc_switch_enter_lightweight_mode,
            cc_switch::commands::lightweight::cc_switch_exit_lightweight_mode,
            cc_switch::commands::lightweight::cc_switch_is_lightweight_mode,
            cc_switch::commands::mcp::cc_switch_delete_claude_mcp_server,
            cc_switch::commands::mcp::cc_switch_delete_mcp_server,
            cc_switch::commands::mcp::cc_switch_delete_mcp_server_in_config,
            cc_switch::commands::mcp::cc_switch_get_claude_mcp_status,
            cc_switch::commands::mcp::cc_switch_get_mcp_config,
            cc_switch::commands::mcp::cc_switch_get_mcp_servers,
            cc_switch::commands::mcp::cc_switch_import_mcp_from_apps,
            cc_switch::commands::mcp::cc_switch_read_claude_mcp_config,
            cc_switch::commands::mcp::cc_switch_set_mcp_enabled,
            cc_switch::commands::mcp::cc_switch_toggle_mcp_app,
            cc_switch::commands::mcp::cc_switch_upsert_claude_mcp_server,
            cc_switch::commands::mcp::cc_switch_upsert_mcp_server,
            cc_switch::commands::mcp::cc_switch_upsert_mcp_server_in_config,
            cc_switch::commands::mcp::cc_switch_validate_mcp_command,
            cc_switch::commands::misc::cc_switch_check_for_updates,
            cc_switch::commands::misc::cc_switch_copy_text_to_clipboard,
            cc_switch::commands::misc::cc_switch_get_init_error,
            cc_switch::commands::misc::cc_switch_get_migration_result,
            cc_switch::commands::misc::cc_switch_get_skills_migration_result,
            cc_switch::commands::misc::cc_switch_get_tool_versions,
            cc_switch::commands::misc::cc_switch_is_portable_mode,
            cc_switch::commands::misc::cc_switch_open_external,
            cc_switch::commands::misc::cc_switch_open_provider_terminal,
            cc_switch::commands::misc::cc_switch_probe_tool_installations,
            cc_switch::commands::misc::cc_switch_run_tool_lifecycle_action,
            cc_switch::commands::misc::cc_switch_set_window_theme,
            cc_switch::commands::omo::cc_switch_disable_current_omo,
            cc_switch::commands::omo::cc_switch_disable_current_omo_slim,
            cc_switch::commands::omo::cc_switch_get_current_omo_provider_id,
            cc_switch::commands::omo::cc_switch_get_current_omo_slim_provider_id,
            cc_switch::commands::omo::cc_switch_read_omo_local_file,
            cc_switch::commands::omo::cc_switch_read_omo_slim_local_file,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_agents_defaults,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_default_model,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_env,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_live_provider,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_live_provider_ids,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_model_catalog,
            cc_switch::commands::openclaw::cc_switch_get_openclaw_tools,
            cc_switch::commands::openclaw::cc_switch_import_openclaw_providers_from_live,
            cc_switch::commands::openclaw::cc_switch_scan_openclaw_config_health,
            cc_switch::commands::openclaw::cc_switch_set_openclaw_agents_defaults,
            cc_switch::commands::openclaw::cc_switch_set_openclaw_default_model,
            cc_switch::commands::openclaw::cc_switch_set_openclaw_env,
            cc_switch::commands::openclaw::cc_switch_set_openclaw_model_catalog,
            cc_switch::commands::openclaw::cc_switch_set_openclaw_tools,
            cc_switch::commands::plugin::cc_switch_apply_claude_onboarding_skip,
            cc_switch::commands::plugin::cc_switch_apply_claude_plugin_config,
            cc_switch::commands::plugin::cc_switch_clear_claude_onboarding_skip,
            cc_switch::commands::plugin::cc_switch_get_claude_plugin_status,
            cc_switch::commands::plugin::cc_switch_is_claude_plugin_applied,
            cc_switch::commands::plugin::cc_switch_read_claude_plugin_config,
            cc_switch::commands::prompt::cc_switch_delete_prompt,
            cc_switch::commands::prompt::cc_switch_enable_prompt,
            cc_switch::commands::prompt::cc_switch_get_current_prompt_file_content,
            cc_switch::commands::prompt::cc_switch_get_prompts,
            cc_switch::commands::prompt::cc_switch_import_prompt_from_file,
            cc_switch::commands::prompt::cc_switch_upsert_prompt,
            cc_switch::commands::provider::cc_switch_add_custom_endpoint,
            cc_switch::commands::provider::cc_switch_add_provider,
            cc_switch::commands::provider::cc_switch_delete_provider,
            cc_switch::commands::provider::cc_switch_delete_universal_provider,
            cc_switch::commands::provider::cc_switch_ensure_claude_desktop_official_provider,
            cc_switch::commands::provider::cc_switch_get_claude_desktop_default_routes,
            cc_switch::commands::provider::cc_switch_get_claude_desktop_status,
            cc_switch::commands::provider::cc_switch_get_current_provider,
            cc_switch::commands::provider::cc_switch_get_custom_endpoints,
            cc_switch::commands::provider::cc_switch_get_opencode_live_provider_ids,
            cc_switch::commands::provider::cc_switch_get_providers,
            cc_switch::commands::provider::cc_switch_get_universal_provider,
            cc_switch::commands::provider::cc_switch_get_universal_providers,
            cc_switch::commands::provider::cc_switch_import_claude_desktop_providers_from_claude,
            cc_switch::commands::provider::cc_switch_import_default_config,
            cc_switch::commands::provider::cc_switch_import_opencode_providers_from_live,
            cc_switch::commands::provider::cc_switch_queryProviderUsage,
            cc_switch::commands::provider::cc_switch_read_live_provider_settings,
            cc_switch::commands::provider::cc_switch_remove_custom_endpoint,
            cc_switch::commands::provider::cc_switch_remove_provider_from_live_config,
            cc_switch::commands::provider::cc_switch_switch_provider,
            cc_switch::commands::provider::cc_switch_sync_universal_provider,
            cc_switch::commands::provider::cc_switch_testUsageScript,
            cc_switch::commands::provider::cc_switch_test_api_endpoints,
            cc_switch::commands::provider::cc_switch_update_endpoint_last_used,
            cc_switch::commands::provider::cc_switch_update_provider,
            cc_switch::commands::provider::cc_switch_update_providers_sort_order,
            cc_switch::commands::provider::cc_switch_upsert_universal_provider,
            cc_switch::commands::proxy::cc_switch_get_circuit_breaker_config,
            cc_switch::commands::proxy::cc_switch_get_circuit_breaker_stats,
            cc_switch::commands::proxy::cc_switch_get_default_cost_multiplier,
            cc_switch::commands::proxy::cc_switch_get_global_proxy_config,
            cc_switch::commands::proxy::cc_switch_get_pricing_model_source,
            cc_switch::commands::proxy::cc_switch_get_provider_health,
            cc_switch::commands::proxy::cc_switch_get_proxy_config,
            cc_switch::commands::proxy::cc_switch_get_proxy_config_for_app,
            cc_switch::commands::proxy::cc_switch_get_proxy_status,
            cc_switch::commands::proxy::cc_switch_get_proxy_takeover_status,
            cc_switch::commands::proxy::cc_switch_is_live_takeover_active,
            cc_switch::commands::proxy::cc_switch_is_proxy_running,
            cc_switch::commands::proxy::cc_switch_reset_circuit_breaker,
            cc_switch::commands::proxy::cc_switch_set_default_cost_multiplier,
            cc_switch::commands::proxy::cc_switch_set_pricing_model_source,
            cc_switch::commands::proxy::cc_switch_set_proxy_takeover_for_app,
            cc_switch::commands::proxy::cc_switch_start_proxy_server,
            cc_switch::commands::proxy::cc_switch_stop_proxy_server,
            cc_switch::commands::proxy::cc_switch_stop_proxy_with_restore,
            cc_switch::commands::proxy::cc_switch_switch_proxy_provider,
            cc_switch::commands::proxy::cc_switch_update_circuit_breaker_config,
            cc_switch::commands::proxy::cc_switch_update_global_proxy_config,
            cc_switch::commands::proxy::cc_switch_update_proxy_config,
            cc_switch::commands::proxy::cc_switch_update_proxy_config_for_app,
            cc_switch::commands::s3_sync::cc_switch_s3_sync_download,
            cc_switch::commands::s3_sync::cc_switch_s3_sync_fetch_remote_info,
            cc_switch::commands::s3_sync::cc_switch_s3_sync_save_settings,
            cc_switch::commands::s3_sync::cc_switch_s3_sync_upload,
            cc_switch::commands::s3_sync::cc_switch_s3_test_connection,
            cc_switch::commands::session_manager::cc_switch_delete_session,
            cc_switch::commands::session_manager::cc_switch_delete_sessions,
            cc_switch::commands::session_manager::cc_switch_get_session_messages,
            cc_switch::commands::session_manager::cc_switch_launch_session_terminal,
            cc_switch::commands::session_manager::cc_switch_list_sessions,
            cc_switch::commands::settings::cc_switch_check_app_update_available,
            cc_switch::commands::settings::cc_switch_get_app_config_dir_override,
            cc_switch::commands::settings::cc_switch_get_auto_launch_status,
            cc_switch::commands::settings::cc_switch_get_copilot_optimizer_config,
            cc_switch::commands::settings::cc_switch_get_log_config,
            cc_switch::commands::settings::cc_switch_get_optimizer_config,
            cc_switch::commands::settings::cc_switch_get_rectifier_config,
            cc_switch::commands::settings::cc_switch_get_settings,
            cc_switch::commands::settings::cc_switch_has_codex_unify_history_backup,
            cc_switch::commands::settings::cc_switch_install_update_and_restart,
            cc_switch::commands::settings::cc_switch_restart_app,
            cc_switch::commands::settings::cc_switch_restore_codex_unified_history,
            cc_switch::commands::settings::cc_switch_save_settings,
            cc_switch::commands::settings::cc_switch_set_app_config_dir_override,
            cc_switch::commands::settings::cc_switch_set_auto_launch,
            cc_switch::commands::settings::cc_switch_set_copilot_optimizer_config,
            cc_switch::commands::settings::cc_switch_set_log_config,
            cc_switch::commands::settings::cc_switch_set_optimizer_config,
            cc_switch::commands::settings::cc_switch_set_rectifier_config,
            cc_switch::commands::skill::cc_switch_add_skill_repo,
            cc_switch::commands::skill::cc_switch_check_skill_updates,
            cc_switch::commands::skill::cc_switch_delete_skill_backup,
            cc_switch::commands::skill::cc_switch_discover_available_skills,
            cc_switch::commands::skill::cc_switch_get_installed_skills,
            cc_switch::commands::skill::cc_switch_get_skill_backups,
            cc_switch::commands::skill::cc_switch_get_skill_repos,
            cc_switch::commands::skill::cc_switch_get_skills,
            cc_switch::commands::skill::cc_switch_get_skills_for_app,
            cc_switch::commands::skill::cc_switch_import_skills_from_apps,
            cc_switch::commands::skill::cc_switch_install_skill,
            cc_switch::commands::skill::cc_switch_install_skill_for_app,
            cc_switch::commands::skill::cc_switch_install_skill_unified,
            cc_switch::commands::skill::cc_switch_install_skills_from_zip,
            cc_switch::commands::skill::cc_switch_migrate_skill_storage,
            cc_switch::commands::skill::cc_switch_remove_skill_repo,
            cc_switch::commands::skill::cc_switch_restore_skill_backup,
            cc_switch::commands::skill::cc_switch_scan_unmanaged_skills,
            cc_switch::commands::skill::cc_switch_search_skills_sh,
            cc_switch::commands::skill::cc_switch_toggle_skill_app,
            cc_switch::commands::skill::cc_switch_uninstall_skill,
            cc_switch::commands::skill::cc_switch_uninstall_skill_for_app,
            cc_switch::commands::skill::cc_switch_uninstall_skill_unified,
            cc_switch::commands::skill::cc_switch_update_skill,
            cc_switch::commands::stream_check::cc_switch_get_stream_check_config,
            cc_switch::commands::stream_check::cc_switch_save_stream_check_config,
            cc_switch::commands::stream_check::cc_switch_stream_check_all_providers,
            cc_switch::commands::stream_check::cc_switch_stream_check_provider,
            cc_switch::commands::subscription::cc_switch_get_subscription_quota,
            cc_switch::commands::usage::cc_switch_check_provider_limits,
            cc_switch::commands::usage::cc_switch_delete_model_pricing,
            cc_switch::commands::usage::cc_switch_get_model_pricing,
            cc_switch::commands::usage::cc_switch_get_model_stats,
            cc_switch::commands::usage::cc_switch_get_provider_stats,
            cc_switch::commands::usage::cc_switch_get_request_detail,
            cc_switch::commands::usage::cc_switch_get_request_logs,
            cc_switch::commands::usage::cc_switch_get_usage_data_sources,
            cc_switch::commands::usage::cc_switch_get_usage_summary,
            cc_switch::commands::usage::cc_switch_get_usage_summary_by_app,
            cc_switch::commands::usage::cc_switch_get_usage_trends,
            cc_switch::commands::usage::cc_switch_sync_session_usage,
            cc_switch::commands::usage::cc_switch_update_model_pricing,
            cc_switch::commands::webdav_sync::cc_switch_webdav_sync_download,
            cc_switch::commands::webdav_sync::cc_switch_webdav_sync_fetch_remote_info,
            cc_switch::commands::webdav_sync::cc_switch_webdav_sync_save_settings,
            cc_switch::commands::webdav_sync::cc_switch_webdav_sync_upload,
            cc_switch::commands::webdav_sync::cc_switch_webdav_test_connection,
            cc_switch::commands::workspace::cc_switch_delete_daily_memory_file,
            cc_switch::commands::workspace::cc_switch_list_daily_memory_files,
            cc_switch::commands::workspace::cc_switch_open_workspace_directory,
            cc_switch::commands::workspace::cc_switch_read_daily_memory_file,
            cc_switch::commands::workspace::cc_switch_read_workspace_file,
            cc_switch::commands::workspace::cc_switch_search_daily_memory_files,
            cc_switch::commands::workspace::cc_switch_write_daily_memory_file,
            cc_switch::commands::workspace::cc_switch_write_workspace_file,
            // projects / sessions
            commands::sessions::list_sessions,
            commands::sessions::create_session,
            commands::sessions::get_session,
            // filesystem
            commands::fs::read_dir,
            commands::fs::read_file,
            commands::fs::write_file,
            commands::fs::open_directory,
            // AI
            commands::ai::call_ai,
            commands::ai::stream_ai,
            commands::ai::send_chat_message,
            commands::ai::cancel_ai,
            // agents
            commands::agents::list_agents,
            commands::agents::get_agent_config,
            commands::agents::set_agent_config,
            commands::agents::clear_agent_config,
            commands::agents::switch_agent,
            commands::agents::current_agent,
            commands::agents::check_agent_health,
            // permissions
            commands::permissions::approve_permission,
            commands::permissions::deny_permission,
            commands::permissions::list_pending_permissions,
            commands::permissions::request_permission,
            // proxy
            commands::proxy::get_proxy_status,
            commands::proxy::start_proxy,
            commands::proxy::stop_proxy,
            // experts
            commands::experts::list_experts,
            commands::experts::create_expert,
            commands::experts::update_expert,
            commands::experts::delete_expert,
            commands::experts::toggle_expert_active,
            commands::experts::scan_expert_files,
            commands::experts::import_expert_to_project,
            // product_changes (cross-conversation artifact ledger)
            commands::product_changes::record_product_change,
            commands::product_changes::record_product_changes_batch,
            commands::product_changes::list_product_changes,
            commands::product_changes::list_product_changes_aggregate,
            skills::commands::tools::get_tool_status,
            skills::commands::tools::set_tool_enabled,
            skills::commands::tools::set_all_tools_enabled,
            skills::commands::tools::get_tool_order_cmd,
            skills::commands::tools::set_tool_order_cmd,
            skills::commands::tools::set_custom_tool_path,
            skills::commands::tools::reset_custom_tool_path,
            skills::commands::tools::set_custom_tool_project_path,
            skills::commands::tools::reset_custom_tool_project_path,
            skills::commands::tools::add_custom_tool,
            skills::commands::tools::remove_custom_tool,
            skills::commands::skills::get_managed_skills,
            skills::commands::skills::get_skills_for_preset,
            skills::commands::skills::get_skill_document,
            skills::commands::skills::get_source_skill_document,
            skills::commands::skills::get_skill_source_diff,
            skills::commands::skills::delete_managed_skill,
            skills::commands::skills::delete_managed_skills,
            skills::commands::skills::install_local,
            skills::commands::skills::install_git,
            skills::commands::skills::preview_git_install,
            skills::commands::skills::confirm_git_install,
            skills::commands::skills::cancel_git_preview,
            skills::commands::skills::install_from_skillssh,
            skills::commands::skills::check_skill_update,
            skills::commands::skills::check_all_skill_updates,
            skills::commands::skills::update_skill,
            skills::commands::skills::batch_update_skills,
            skills::commands::skills::reimport_local_skill,
            skills::commands::skills::relink_local_skill_source,
            skills::commands::skills::detach_local_skill_source,
            skills::commands::skills::get_all_tags,
            skills::commands::skills::set_skill_tags,
            skills::commands::skills::rename_tag,
            skills::commands::skills::delete_tag,
            skills::commands::skills::cancel_install,
            skills::commands::skills::batch_import_folder,
            skills::commands::sync::sync_skill_to_tool,
            skills::commands::sync::unsync_skill_from_tool,
            skills::commands::sync::get_skill_tool_toggles,
            skills::commands::sync::set_skill_tool_toggle,
            skills::commands::scan::scan_local_skills,
            skills::commands::scan::import_existing_skill,
            skills::commands::scan::import_all_discovered,
            skills::commands::browse::fetch_leaderboard,
            skills::commands::browse::search_skillssh,
            skills::commands::settings::get_settings,
            skills::commands::settings::set_settings,
            skills::commands::settings::get_central_repo_path,
            skills::commands::settings::get_central_repo_path_override,
            skills::commands::settings::get_central_repo_warnings,
            skills::commands::settings::set_central_repo_path,
            skills::commands::settings::open_central_repo_folder,
            skills::commands::settings::check_app_update,
            skills::commands::settings::get_diagnostic_info,
            skills::commands::settings::get_recent_log_excerpt,
            skills::commands::settings::export_logs_zip,
            skills::commands::settings::log_startup_event,
            skills::commands::settings::check_last_panic,
            skills::commands::settings::clear_last_panic,
            skills::commands::settings::app_exit,
            skills::commands::settings::hide_to_tray,
            skills::commands::git_backup::git_backup_fetch,
            skills::commands::git_backup::git_backup_status,
            skills::commands::git_backup::git_backup_init,
            skills::commands::git_backup::git_backup_set_remote,
            skills::commands::git_backup::git_backup_remove_remote,
            skills::commands::git_backup::git_backup_commit,
            skills::commands::git_backup::git_backup_push,
            skills::commands::git_backup::git_backup_pull,
            skills::commands::git_backup::git_backup_clone,
            skills::commands::git_backup::git_backup_reclone,
            skills::commands::git_backup::git_backup_create_snapshot,
            skills::commands::git_backup::git_backup_list_versions,
            skills::commands::git_backup::git_backup_restore_version,
            skills::commands::projects::get_projects,
            skills::commands::projects::skills_add_project,
            skills::commands::projects::add_linked_workspace,
            skills::commands::projects::skills_remove_project,
            skills::commands::projects::scan_projects,
            skills::commands::projects::get_project_agent_targets,
            skills::commands::projects::get_project_skills,
            skills::commands::projects::get_project_skill_document,
            skills::commands::projects::import_project_skill_to_center,
            skills::commands::projects::export_skill_to_project,
            skills::commands::projects::update_project_skill_to_center,
            skills::commands::projects::update_project_skill_from_center,
            skills::commands::projects::toggle_project_skill,
            skills::commands::projects::delete_project_skill,
            skills::commands::projects::slugify_skill_names,
            skills::commands::agent_workspace::get_global_local_skills,
            skills::commands::agent_workspace::get_global_local_skill_document,
            skills::commands::agent_workspace::import_global_local_skill_to_center,
            skills::commands::agent_workspace::update_global_local_skill_from_center,
            skills::commands::agent_workspace::delete_global_local_skill,
            skills::commands::presets::get_presets,
            skills::commands::presets::get_active_preset,
            skills::commands::presets::create_preset,
            skills::commands::presets::update_preset,
            skills::commands::presets::delete_preset,
            skills::commands::presets::switch_preset,
            skills::commands::presets::apply_preset_to_default,
            skills::commands::presets::apply_preset_to_coding_agents,
            skills::commands::presets::add_skill_to_preset,
            skills::commands::presets::remove_skill_from_preset,
            skills::commands::presets::reorder_presets,
            skills::commands::projects::reorder_projects,
            skills::commands::presets::get_preset_skill_order,
            skills::commands::presets::reorder_preset_skills,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
